containersUnderTest:
  ? namespace: default
    podName: test
    containerName: test
  : defaultNetworkDevice: eth0
    multusIpAddresses:
      - 192.168.1.1
partnerContainers:
  ? namespace: default
    podName: partner
    containerName: partner
  : defaultNetworkDevice: eth0
    multusIpAddresses:
      - 192.168.1.3
testOrchestrator:
  namespace: default
  podName: partner
  containerName: partner
turniumBonder:
  namespace: default
  podName: bonder
  containerName: bonder